MovieReview/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path("Movielist/", include('Movielist.urls')) 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Movielist/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Movie, name='index'),
    path('filldata/', views.filldetails),
    path('savedata/', views.InsertData, name='savedata'),
    path('search/', views.search, name= 'search')
]

Movielist/models.py
from django.db import models

class moviel(models.Model):
    MovieName = models.CharField(max_length=100)
    Budget = models.IntegerField()
    IMDBrating = models.IntegerField()
    Movieinfo=models.CharField(max_length=400)
    link = models.CharField(max_length=400)
    image = models.ImageField(upload_to='Movielist/images')
    def __str__(self):
        return self.MovieName
# Create your models here.

MovieReview/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

Movielist/views.py
from django.shortcuts import render
from .models import moviel

def filldetails(request):
    return render(request, 'Movielist/Updatelist.html')

def Movie(request):
    movielist = moviel.objects.all()
    return render(request, 'Movielist/Movieslist.html', {'moviel': movielist})


def InsertData(request):
    MovieName = request.POST.get('MovieName')
    Budget= request.POST.get('Budget')
    IMDBrating = request.POST.get('IMDBrating')
    Movieinfo = request.POST.get('Movieinfo')
    link=request.POST.get('link')
    image=request.POST.get('image')
    movie_list=moviel(MovieName=MovieName,Budget=Budget,IMDBrating=IMDBrating,Movieinfo=Movieinfo,link=link,image=image)
    movie_list.save()
    return render(request, 'Movielist/Updatelist.html')

def search(request):
    query=request.GET.get('search')
    allPost=moviel.objects.filter(MovieName__icontains=query)
    params={'moviel': allPost, 'query': query}
    return render(request, 'Movielist/Search.html', params)

MovieReview/templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <title>Welcome To Bollywood Box Office</title>
  </head>
  <body>
    <div class="jumbotron">
  <h1 class="display-4">Welcome To Bollywood Box Office</h1>
  <p class="lead"> Now visit the movie list to see all latest movie list and you want update the list you can do as well with below button</p>
  <hr class="my-4">
  <p>Check out the list of Bollywood movie</p>
  <a class="btn btn-primary btn-lg" href="/Movielist" role="button">Movie list</a><br>
  <p>Want to add movie, please click on below button</p>
  <a class="btn btn-primary btn-lg" href="/Movielist/filldata" role="button">Add new Movie</a>
</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!--<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  -->
  </body>
</html>

Movielist/templates/Movielist/Movieslist.html
{% extends 'Movielist/basic.html' %}
{% block title %}Blood donor list{% endblock%}
{% block body %}
     {% load static %}
    <h1>LIST OF Bollywood and Hollywood movies</h1>
  <table class="table">
  <thead>
    <tr>
      <th scope="col">Movie Name</th>
      <th scope="col">Budget</th>
      <th scope="col">IMDB Rating</th>
      <th scope="col">Movie Details</th>
    </tr>
  </thead>
    {% for datadisplay in moviel %}
  <tbody>
    <tr>
      <td> <a href="{{datadisplay.link}}" target="_blank" rel="noopener"><b><img src="/media/{{datadisplay.image}}"
      height="200" width="400">
        <br>
        {{datadisplay.MovieName}}&nbsp;</b></a></td>
      <th>{{datadisplay.Budget}}</th>
      <td>{{datadisplay.IMDBrating}}</td>
      <td>{{datadisplay.Movieinfo}}</td>
    </tr>
  </tbody>
    {% endfor %}
</table>
{% endblock %}

Movielist/templates/Movielist/Search.html
{% extends 'Movielist/basic.html' %}
{% block title %}Bollywood movie list{% endblock %}
{% block body %}
     {% load static %}
    {% if moviel|length < 1 %}
      <p>Sorry your searched movie is not found</p>
      Your search movie : <b>{{query}}</b> did not match with any movie. <br>
      Suggestions :
      <ul><li>Try with different movie name</li></ul>
    {% else %}
    <h1>Your Movie is here</h1>
      <table class="table">
  <thead>
    <tr>
      <th scope="col">Movie Name</th>
      <th scope="col">Budget</th>
      <th scope="col">IMDB Rating</th>
      <th scope="col">Movie Details</th>
    </tr>
  </thead>
    {% for datadisplay in moviel %}
  <tbody>
    <tr>
      <td> <a href="{{datadisplay.link}}" target="_blank" rel="noopener"><b><img src="/media/{{datadisplay.image}}"
      height="200" width="400">
        <br>
        {{datadisplay.MovieName}}&nbsp;</b></a></td>
      <th>{{datadisplay.Budget}}</th>
      <td>{{datadisplay.IMDBrating}}</td>
      <td>{{datadisplay.Movieinfo}}</td>
    </tr>
  </tbody>
    {% endfor %}
</table>
    {% endif %}

{% endblock %}

Movielist/templates/Movielist/Updatelist.html
{% extends 'Movielist/basic.html' %}
{% block title %}Blood donor details{% endblock%}
{% block css %}
input[type=text], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}
input[type=submit] {
  width: 100%;
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}
{% endblock %}

{% block body %}
{% load static %}
<br>
<h1>Please Add the movie details below</h1>
<div style="border-radius: 5px;background-color: #f2f2f2;padding: 20px;">
  <form action="{% url 'savedata' %}" method="post">
    {% csrf_token %}
    <label for="fname">Movie Name</label>
    <input type="text" id="fname" name="MovieName" placeholder="Enter the Movie name..">

    <label for="lname">Budget(in cr)</label>
    <input type="text" id="lname" name="Budget" placeholder="Enter the Budget of movie...">

    <label for="imdb">IMDB rating</label>
    <input type="text" id="imdb" name="IMDBrating" placeholder="Enter IMDB rating of movie...">

    <label for="locat">Movie information</label>
    <input type="text" id="locat" name="Movieinfo" placeholder="Please add something about movie...">

    <label for="minfo">link of movie</label>
    <input type="text" id="minfo" name="link" placeholder="Please paste the link of movie...">

    <label class="required" for="id_image">Image:</label>
    <input type="file" name="image" accept="Movielist/images" required="" id="id_image">

    <input type="submit" value="Submit" >
  </form>
</div>
{% endblock %}

Movielist/templates/Movielist/basic.html
<!DOCTYPE html>
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>{% block title %} {% endblock %}</title>
    <style>
      {% block css %} {% endblock %}
    </style>

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/Movielist">Movie List</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/Movielist/filldata">Add new Movie</a>
        </li>
      </ul>
    </div>
    <form class="d-flex" method="get" action="{% url 'search' %}">
      <input class="form-control me-2" name="search" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </div>
</nav>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  {% block body %} {% endblock %}
  </body>
</html>